pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Setup environment') {
            steps {
                echo 'setup environment'
            }
        }
        stage('Download dependencies') {
            steps {
                dir('Frontend') {
                    sh 'npm install'
                }
            }
        }
        stage('Deploy development branch') {
            steps {
                echo 'automatic deploy development branch to heroku'
            }
        }
        stage('Unit testing with coverage') {
            steps {
                dir('Frontend') {
                    sh 'npm run test-unit'
                }
            }
        }
        stage('Component testing with coverage') {
            steps {
                echo 'run component testing'
            }
        }
        stage('Integration testing with coverage') {
            steps {
                dir('Frontend') {
                    sh 'npm run test-integration'
                }
            }
        }
        stage('E2E testing with coverage') {
            steps {
                dir('Frontend') {
                    sh 'npm run test-e2e'
                }
            }
        }
        stage('Deploy main branch') {
            steps {
                echo 'automatic deploy main branch to heroku and docker'
                withCredentials([string(credentialsId: 'T12_ROOTPASS_SECRET', variable: 'rootpass')]) {
                    script {
                        def remote = [:]
                        remote.name = 'T12'
                        remote.host = '159.65.12.177'
                        remote.user = 'root'
                        remote.password = "${rootpass}"
                        remote.allowAnyHosts = true
                        sshCommand remote: remote, command: 'git clone https://github.com/bambam4334/Project-SW-Dev.git'
                        sshCommand remote: remote, command: 'docker-compose -f Project-SW-Dev/Frontend/docker-compose.yml up -d'
                        sshCommand remote: remote, command: 'rm -r Project-SW-Dev'
                    }
                }
            }
        }
        post { 
            always { 
                cleanWs()
            }
        }
    }
}

